//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Net.Demandware.Ocapi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Net.Demandware.Ocapi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content folder IDs array must contain fewer than 50 items..
        /// </summary>
        internal static string Error_Folder_ID_Out_Of_Range {
            get {
                return ResourceManager.GetString("Error_Folder_ID_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid address name must be provided..
        /// </summary>
        internal static string Error_Missing_Address_Name {
            get {
                return ResourceManager.GetString("Error_Missing_Address_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid basket ID must be provided..
        /// </summary>
        internal static string Error_Missing_Basket_ID {
            get {
                return ResourceManager.GetString("Error_Missing_Basket_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid category ID must be provided..
        /// </summary>
        internal static string Error_Missing_Category_ID {
            get {
                return ResourceManager.GetString("Error_Missing_Category_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid content asset ID must be provided..
        /// </summary>
        internal static string Error_Missing_Content_ID {
            get {
                return ResourceManager.GetString("Error_Missing_Content_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid key attribute value must be provided..
        /// </summary>
        internal static string Error_Missing_Custom_Object_Key {
            get {
                return ResourceManager.GetString("Error_Missing_Custom_Object_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid custom object type must be provided..
        /// </summary>
        internal static string Error_Missing_Custom_Object_Type {
            get {
                return ResourceManager.GetString("Error_Missing_Custom_Object_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid customer ID must be provided..
        /// </summary>
        internal static string Error_Missing_Customer_ID {
            get {
                return ResourceManager.GetString("Error_Missing_Customer_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid content folder ID must be provided..
        /// </summary>
        internal static string Error_Missing_Folder_ID {
            get {
                return ResourceManager.GetString("Error_Missing_Folder_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid query string must be provided..
        /// </summary>
        internal static string Error_Missing_Query_String {
            get {
                return ResourceManager.GetString("Error_Missing_Query_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query count must be greater than 1 and less than 200..
        /// </summary>
        internal static string Error_Query_Count_Out_Of_Range {
            get {
                return ResourceManager.GetString("Error_Query_Count_Out_Of_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query string must be 50 characters or fewer..
        /// </summary>
        internal static string Error_Query_String_Length {
            get {
                return ResourceManager.GetString("Error_Query_String_Length", resourceCulture);
            }
        }
    }
}
